version: "3"

services:
  redis:
    image: redis:6.2-alpine
    container_name: cache
    restart: unless-stopped
    # command: [ "redis-server", "--bind", "redis", "--port", "6379" ]
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
  app:
    build: .
    container_name: app
    # restart: unless-stopped
    # network_mode: bridge
    # networks:
    #   - backend
    volumes:
      - ./:/dist
      - /node_modules
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - redis
    # networks:
    #   backend:
    #docker-compose up -d 
    #docker exec -it <container-name> bash
